spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show_sql: true
      format_sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  frontend-url: ${FRONTEND_URL}
  scheduler:
    enabled: true
    user-cleanup-cron: "0 0 2 * * *"  # 매일 새벽 2시
    max-retries: 3